### ISSUE TITLE
Use of undeclared identifier on Mac ARM

### ISSUE THREAD

**Issue by couet** [root-project/root#10548]
### Describe the bug

On Mac ARM we get (found by René):

```
sftnight@macphsft26 build % root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern/ |
  | (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosxarm64 on May 09 2022, 11:42:50                   |
  | From heads/master@v6-25-02-1202-g8dc4bc40fb                      |
  | With Apple clang version 13.1.6 (clang-1316.0.21.2.3)            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] whatever
input_line_9:2:3: error: use of undeclared identifier 'whatever'
 (whatever)
  ^
libc++abi: terminating with uncaught exception of type cling::CompilationException
sftnight@macphsft26 build %
```

### Expected behavior
```
% root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosx64 on May 09 2022, 05:37:55                      |
  | From heads/master@v6-25-02-1201-g797bb5dce1                      |
  | With Apple clang version 13.1.6 (clang-1316.0.21.2.3)            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] whatever
input_line_13:2:3: error: use of undeclared identifier 'whatever'
 (whatever)
  ^
Error in <HandleInterpreterException>: Error evaluating expression (whatever)
Execution of your code was aborted.
root [1] 
```
### To Reproduce
Type something unknown at the ROOT prompt.

### Setup
MacOS, ARM1 machine

**Comment by vgvassilev** [comment]
@hahnjo, I thought we fixed this?

**Comment by hahnjo** [comment]
No, #7541 is still not fixed, waiting for Apple to fix their `libunwind` before we can do anything about it in general. This one shouldn't happen though, I thought Axel updated Cling to not `throw` exceptions...

**Comment by vgvassilev** [comment]
Maybe a missing backport?

**Comment by hahnjo** [comment]
Ah, https://github.com/root-project/root/pull/7744 only concerned `cling_runtime_internal_throwIfInvalidPointer`. We could disable the `throw` in `CompilationException::throwingHandler` as we already do for `_MSC_VER`, not sure what happens in that case...

**Comment by vgvassilev** [comment]
cc: @Axel-Naumann

**Comment by Axel-Naumann** [comment]
> We could disable the throw in CompilationException::throwingHandler as we already do for _MSC_VER, not sure what happens in that case...

Agreed, we need to return 'error'. This is what was happening before; I'd hope that it's still an option. @hahnjo do you think you can have a look or should I?

**Comment by hahnjo** [comment]
> Agreed, we need to return 'error'. This is what was happening before; I'd hope that it's still an option. @hahnjo do you think you can have a look or should I?

If it's as easy as "commenting out" the `throw`, I can have a look. Hopefully I don't have to introduce a new scheme for returning  / propagating the error in the absence of exceptions...

**Comment by hahnjo** [comment]
With https://github.com/root-project/root/pull/10561, the behavior on M1 should be:
```
root [0] whatever
input_line_9:2:3: error: use of undeclared identifier 'whatever'
 (whatever)
  ^
root [1]
```
ie, the error is still reported but there is no exception thrown.
