### ISSUE TITLE
[RF] MultiProcess README.md should be updated to include LikelihoodJob

### ISSUE THREAD

**Issue by egpbos** [root-project/root#10967]
#10966 fixes LikelihoodJob so that it can now be used for parallelizing non-gradient parts of the migrad minimization. This should be reflected in the relevant README.md section here: https://github.com/root-project/root/tree/master/roofit/roofitcore/src/TestStatistics#calculators

We have yet to thoroughly test the class on real life fits. We intend to do this in the coming weeks. After this, we will rewrite the docs, taking into account any possible fixes or API changes that may have been necessary after our tests.

**Comment by dpiparo** [comment]
I assume the issue is fixed as I do not find any https://github.com/root-project/root/tree/master/roofit/roofitcore/src/TestStatistics#calculators (or even similar files). Still, I could be wrong: in this case please do not hesitate to reopen the issue, with some context to highlight a path for the fix.

**Comment by egpbos** [comment]
The issue is not fixed, but the relevant files have been moved to the RooFit developers manual: https://github.com/root-project/root/blob/master/roofit/doc/developers/test_statistics.md

I will update this soon; I have already been drafting a new text, but other priorities prevented me from finishing it yet.
