### ISSUE TITLE
TCanvas size is inconsistent in batch vs non-batch mode

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#11004]
- [x] Checked for duplicates

### Describe the bug
I see one small issue when saving a 600x600 TCanvas window as png.

I get:
- Interactive mode: 598x571 pixels
- Batch mode: 596x572 pixels

### Expected behavior
No pixel difference is found between running batch or not. Right now there is an offset of 1 up to 2 pixels.

### To Reproduce

```cpp
void test() {
    TCanvas *c = new TCanvas("c1","c1",600,600);
    c->SaveAs("c1.png");
}
//root -l test.C -b -q
//root -l test.C -q
```

### Setup
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jan 11 2022, 18:39:08                 |
  | From heads/master@v6-25-01-2870-gdac9b6398d                      |
  | With c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0                     |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

**Comment by couet** [comment]
I do not think there is a lot we can do. The png file is not a screen copy and some rouning issues in completely different code might be possible. I propose to close this issue.

**Comment by ferdymercury** [comment]
In my other computer, I get now a difference of 4 pixels using latest ROOT master. So it seems to me that this is not a small rounding error.

- Interactive mode: 598x576 pixels
- Batch mode: 596x572 pixels


Could it be just an outdated calibration from many years ago? See this https://github.com/root-project/root/commit/c3de92f4d1ad4372febc81955a877345d4de3a9c

Check out this code below. It seems there is always the same offset on my current computer. Whenever I run in batch mode, I get 4 pixels difference wrt batch mode. My hypothesis is that this could solved if those numbers are adapted, potentially depending on Windows / Mac with an if. It could be even added as a roottest.

```cpp
// Run either as root -l test_pixels.cpp -b -q
// Or as xvfb-run root -l test_pixels.cpp -q
#include <TCanvas.h>
#include <TROOT.h>
#include <iostream>
void test_pixels() {
    for(Int_t w=500;w<=900;w++) {
        for(Int_t h=500;h<=600;h++) {
            TCanvas *c = new TCanvas("c1","c1",w,h);
            Int_t diffw = w-c->GetWw();
            Int_t diffh = h-c->GetWh();
            if(!gROOT->IsBatch()) {
                if (diffw !=2 || diffh !=24)
                    std::cout << diffw << " " << diffh << " " << w << " " << h << std::endl;
            }
            else {
                if (diffw !=4 || diffh !=28)
                    std::cout << diffw << " " << diffh << " " << w << " " << h << std::endl;
            }
            delete c;
        }
    }
}
```

**Comment by couet** [comment]
ok, I'll look again ...

**Comment by couet** [comment]
I am not sure we need to spend to much time on this issue as the new default graphics will be soon the one in the Web Browser. In the case the size of the canvas is completly different. There is a new PR on the way. In the master only for the time being.

**Comment by dpiparo** [comment]
I cannot understand from the conversation: is the issue fixed now?

**Comment by ferdymercury** [comment]
No, it's not fixed, the script reproducing it is https://github.com/root-project/root/issues/11004#issuecomment-1471869803

Though low priority ...

**Comment by ferdymercury** [comment]
Another occurrence in the forum: https://root-forum.cern.ch/t/dimension-changes-in-saveas-canvas-for-batch-mode/63385

**Comment by rlalik** [comment]
As I just learned about this thread, I see this is long standing issue I was also concerned, I preapred a draft for now for a solution to the problem: #21156 - now `TCanvas` arguments would be true canavs size, not window size.

**Comment by rlalik** [comment]
And this is also is related to the topic but on less direct way. The fact that the canvases have slightly different size than assumed from `TCanvas` arguments, the labels scaling and distances are inconsistent visually (but consistent with the logic):
https://root-forum.cern.ch/t/title-and-label-size-scaling-inconsistent-behaviour/64168

**Comment by couet** [comment]
Looking at it in the Fixathon 20 context

**Comment by couet** [comment]
I made a PR addressing this issue: https://github.com/root-project/root/pull/22226

**Comment by ferdymercury** [comment]
Considering the discussion in the associated PRs, and the fact that there is no clear way out for solving this issue without breaking backward compatibility or without introducing an ugly rootrc extra interface, and that there is a workaround documented, I will close this issue as won't fix.
