### ISSUE TITLE
compiling v6.28.02 fails under opensuse TW with gcc-13

### ISSUE THREAD

**Issue by svenmenke** [root-project/root#12659]
Dear all,

after 

git clone https://github.com/root-project/root.git
cd root
git checkout -b v6-28-02 v6-28-02
mkdir root_build
cd root_build
cmake ../root
cmake --build -j4

I get:
...
[ 75%] Built target rootcling_stage1
[ 75%] Generating G__Core.cxx, ../lib/Core.pcm
While building module 'Core':
While building module 'std' imported from input_line_1:1:
In file included from <module-includes>:4:
In file included from /usr/include/c++/13/bitset:52:
In file included from /usr/include/c++/13/string:47:
/usr/include/c++/13/bits/stl_iterator_base_funcs.h:81:5: error: redefinition of '__distance'
    __distance(_InputIterator __first, _InputIterator __last,
    ^
/usr/include/c++/13/bits/stl_iterator_base_funcs.h:81:5: note: previous definition is here
    __distance(_InputIterator __first, _InputIterator __last,
    ^
...

This is under opensuse Tumbleweed with latest updates. The default compiler is gcc-13. 

It looks similar to an previous issue with gcc-12: https://github.com/root-project/root/issues/10478

The last time I built root (v6.26.10 in December 2022) I had no problems but I don't know what the gcc version was back then. 
Could you please have a look?
Thanks & Cheers,
--Sven

**Comment by Axel-Naumann** [comment]
Can you confirm that this is fixed with [v6-28-00-patches](https://github.com/root-project/root/pull/12714)?

**Comment by svenmenke** [comment]
Hi @Axel-Naumann , 
thanks for the patch!
I get past rootcling and also past Core (the target that failed originally). But soon after it's still failing with
...
 [ 76%] Generating G__XMLIO.cxx, ../../lib/XMLIO.pcm
In file included from input_line_10:3:
/home/menke/Downloads/root_build/include/ROOT/RVec.hxx:54:10: fatal error: 'vdt/vdtMath.h' file not found
#include <vdt/vdtMath.h>
         ^~~~~~~~~~~~~~~
...
Cheers,
--Sven

**Comment by Axel-Naumann** [comment]
D'oh. Can you share your CMakeCache.txt?

**Comment by svenmenke** [comment]
sorry - this was false alarm. I had the prior root build with gcc-12 still in the lib and execute paths ... trying again.
--Sven

**Comment by svenmenke** [comment]
o.k. compile worked now with gcc-13 on TW and root seems to work as expected. Thanks again for the fix.
Cheers,
--Sven

**Comment by Axel-Naumann** [comment]
Thanks for the confirmation!
