### ISSUE TITLE
Can't open TBrowser locally after upgrading macos “Apple M2 14.0 (23A344)”

### ISSUE THREAD

**Issue by WentaiLuo** [root-project/root#13834]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Today I upgraded my macos system to 14.0, downloaded the source code for v6.28/06 and compiled it, after that root works fine and drawing works fine, but TBrowser doesn't work!
![WechatIMG150](https://github.com/root-project/root/assets/61787337/bf938e44-b07b-4760-878a-7600a2e41ee5)

### Reproducer

run root -l
TBrowser a

and saw this picture
![WechatIMG150](https://github.com/root-project/root/assets/61787337/7e8f1a54-9304-49ba-bbd6-c3a088a5a81a)

### ROOT version

v6.28/06 

### Installation method

build from source

### Operating system

MacOS

**Comment by Josiah1** [comment]
I also encountered this problem on the new Macos 14. Even in the ROOT prompt, I can draw plots normally, but if I click the menu "edit" or others, ROOT will crash.

**Comment by bellenot** [comment]
I don't have access to a Mac. Maybe @couet can try?

**Comment by dpiparo** [comment]
I just tried on macos14 and pyroot. The browser opens fine. Can it be linked to the event loop?
In any case the web browser works very well, as a stop gap solution.

**Comment by Josiah1** [comment]
> I just tried on macos14 and pyroot. The browser opens fine. Can it be linked to the event loop? In any case the web browser works very well, as a stop gap solution. What I did not manage to reproduce is the crash upon clicking "Edit" when drawing a plot.

Thanks for trying this. Can you just try the root prompt? And open a TBrowser, or draw a plot and then click the edit menu.

**Comment by couet** [comment]
I just tried:
```
root [0] TBrowser B
```
It is fine with master on my mac
I will build 6.28

**Comment by couet** [comment]
By the way, where did you take root from ? did you built it yourself ?

**Comment by WentaiLuo** [comment]
> By the way, where did you take root from ? did you built it yourself ?

I downloaded the source code from the official website, https://root.cern/releases/release-62806/

I think it's the macos upgrade that's causing this bug, because everything was fine before the upgrade.

**Comment by couet** [comment]
Yes, but on that web page, there is no module for MacOS14 yet. That might be the cause of the problem because when I build it from sources on my MacOS 14 machine I have no problem with TBrowser. The version for macOS14 should come soon. Meanwhile, you can try to build from the sources if you want.

**Comment by couet** [comment]
Do you have an M1 or M2 machine ?

**Comment by WentaiLuo** [comment]
> I also encountered this problem on the new Macos 14. Even in the ROOT prompt, I can draw plots normally, but if I click the menu "edit" or others, ROOT will crash.

Intel machine.

**Comment by couet** [comment]
I just tried with a local build using "master" on my Intel MacOS machine 14.0 23A344 
and it works:
<img width="839" alt="Screenshot 2023-10-11 at 09 19 37" src="https://github.com/root-project/root/assets/4697738/60d1f530-dd59-4a2c-91b9-4e059aeef962">

**Comment by WentaiLuo** [comment]
> I just tried with a local build using "master" on my Intel MacOS machine 14.0 23A344 and it works: <img alt="Screenshot 2023-10-11 at 09 19 37" width="839" src="https://user-images.githubusercontent.com/4697738/274177192-60d1f530-dd59-4a2c-91b9-4e059aeef962.png">

ok, I will try "master" sources.

**Comment by WentaiLuo** [comment]
> I just tried with a local build using "master" on my Intel MacOS machine 14.0 23A344 and it works: <img alt="Screenshot 2023-10-11 at 09 19 37" width="839" src="https://user-images.githubusercontent.com/4697738/274177192-60d1f530-dd59-4a2c-91b9-4e059aeef962.png">

I downloaded the master on github and ran root successfully after cmake.
TBrowser still doesn't work though, luckily the web version works.
<img width="1126" alt="截屏2023-10-11 16 01 39" src="https://github.com/root-project/root/assets/61787337/1481909e-57ea-4c48-84cf-6c64129ab7f2">

**Comment by couet** [comment]
_TBrowser still doesn't work though_

On both Intel and M2 ?

I was also thinking about Xcode, is there any update to be done on your machine(s) ?

**Comment by WentaiLuo** [comment]
> _TBrowser still doesn't work though_
> 
> On both Intel and M2 ?
> 
> I was also thinking about Xcode, is there any update to be done on your machine(s) ?

M2 machine is a new one, so the Xcode is installed for the latest version. Intel machine is my friend's, so I'm not quite sure.

**Comment by couet** [comment]
I have also XCode 15 on my Intel machine

**Comment by couet** [comment]
I see the issue on M2 now

**Comment by couet** [comment]
It does not seem to be blocked because the GUI reacts the pull-down menus from the menu bar display correctly and the fit panel displays correctly also ...

**Comment by couet** [comment]
Some news: We have an M1 machine, `macphsft24`, running MacOS14 but using clang 12.0.5. I installed ROOT master on it and TBrowser is working ... I see the bug on machines running clang 15. Can you type the command `clang --version` on the machines on which TBrowser is failing for you ? to see which version of clang you are using ...

**Comment by couet** [comment]
clang 15 with macos 13.6 is working...

**Comment by WentaiLuo** [comment]
> Some news: We have an M1 machine, `macphsft24`, running MacOS14 but using clang 12.0.5. I installed ROOT master on it and TBrowser is working ... I see the bug on machines running clang 15. Can you type the command `clang --version` on the machines on which TBrowser is failing for you ? to see which version of clang you are using ...

clang version is 15.0.0(clang-1500.0.40.1)

**Comment by WentaiLuo** [comment]
> clang 15 with MacOs 13.6 is working... (M1)
> 
> So it seems we need MacOS 14 AND clang 15 to get the problem.
> 
> Is it the case for the Intel machine of your friend?

The intel machine is also clang 15.0.0 (clang-1500.0.40.1)

**Comment by couet** [comment]
As I told you on the forum, we are on it.

**Comment by BethLong06** [comment]
I have the same issue on intel and Clang 11.0.0 after updating to MacOS14

**Comment by couet** [comment]
I do not see it with Intel Clang 12 and OSX 14. It is strange you see it with Clang 11. I am now updating my Intel machine to Clang 15 (the faulty one). 
Anyway, this PR fixes the problem.

**Comment by couet** [comment]
The PR that fixes these problems is now merged in master.

**Comment by bellenot** [comment]
@couet this is not (yet) fixed in 6.30/00

**Comment by amishgog** [comment]
Hi, TBrowser still doesn't work locally for me on MaCOS 14 and clang 15.0.0
