### ISSUE TITLE
Cannot build root 6.34 on opensuse

### ISSUE THREAD

**Issue by johnpapad24** [root-project/root#18103]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

Dear root team,

I was unable to build root version 6.30.02 from source on fedora 41 and opensuse distributions despite the fact that I have experimented with multiple gcc compiler versions particularly gcc version 10.5 and gcc version 11.5 on both versions.

Below I attach the corresponding errors for fedora and opensuse respectively.

![Image](https://github.com/user-attachments/assets/4c6ad30e-1134-4ffc-b0a8-519b9813027a)

![Image](https://github.com/user-attachments/assets/c7ef57a4-29e2-4075-b00a-1a5b1471c0a5)

I also want to ask if a subproject changes the cmake compiler in the process. 

Thanks in advance.

### Reproducer

Try to build root 6.30.02 from source on fedora 41 and opensuse distributions

### ROOT version

root version 6.30.02

### Installation method

building/compiling from source

### Operating system

Linux: Fedora 41 and opensuse (both tumbleweed and leap)

**Comment by bellenot** [comment]
6.30.02 is most probably too old for recent distributions. Can you try a more recent version of ROOT?

**Comment by johnpapad24** [comment]
I have also tried 6.32.10..

The isssue persists

**Comment by johnpapad24** [comment]
I will try your suggestion but it's preferable not to change root version because its part of a bigger project.

I will also try the same in opensuse and send you the results back.

**Comment by ferdymercury** [comment]
The first error was fixed by @silverweed in https://github.com/root-project/root/commit/a028d13255f0c2d0c84f2e1b99ccb6a112598e0c

So i guess that it could be backported ?

**Comment by johnpapad24** [comment]
v6.34 on fedora ok.

on opensuse the issue persists

![Image](https://github.com/user-attachments/assets/b6cd88bb-f27e-4baa-b0fd-5945465e21c3)

**Comment by johnpapad24** [comment]
Yes i have installed full depedencies and every package that involves fftw3 and libfftw3

**Comment by johnpapad24** [comment]
[ 91%] Building CXX object math/fftw/CMakeFiles/FFTW.dir/src/TFFTReal.cxx.o
cd /home/user/biodynamo/build/build-third-party/build_root/obj/math/fftw && /home/user/biodynamo/third_party/gcc/bin/g++  -I/home/user/biodynamo/build/build-third-party/build_root/math/fftw/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/unix/../clib/res -I/home/user/biodynamo/build/build-third-party/build_root/core/unix/inc -I/home/user/biodynamo/build/build-third-party/build_root/builtins/zstd -I/home/user/biodynamo/build/build-third-party/build_root/core/zstd/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/lz4/inc -I/home/user/biodynamo/build/build-third-party/build_root/obj/include -I/home/user/biodynamo/build/build-third-party/build_root/core/lzma/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/zip/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/thread/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/textinput/src -I/home/user/biodynamo/build/build-third-party/build_root/core/textinput/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/rint/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/meta/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/gui/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/foundation/res -I/home/user/biodynamo/build/build-third-party/build_root/core/foundation/v7/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/foundation/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/cont/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/clingutils/res -I/home/user/biodynamo/build/build-third-party/build_root/core/clingutils/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/clib/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/base/v7/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/base/inc -I/home/user/biodynamo/build/build-third-party/build_root/obj/ginclude -I/home/user/biodynamo/build/build-third-party/build_root/math/mathcore/v7/inc -I/home/user/biodynamo/build/build-third-party/build_root/math/mathcore/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/imt/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/multiproc/inc -I/home/user/biodynamo/build/build-third-party/build_root/net/net/inc -I/home/user/biodynamo/build/build-third-party/build_root/io/io/v7/inc -I/home/user/biodynamo/build/build-third-party/build_root/io/io/inc -std=c++17 -Wno-implicit-fallthrough -Wno-noexcept-type -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -O3 -DNDEBUG -fPIC -std=c++17 -o CMakeFiles/FFTW.dir/src/TFFTReal.cxx.o -c /home/user/biodynamo/build/build-third-party/build_root/math/fftw/src/TFFTReal.cxx
[ 91%] Building CXX object math/fftw/CMakeFiles/FFTW.dir/src/TFFTRealComplex.cxx.o
cd /home/user/biodynamo/build/build-third-party/build_root/obj/math/fftw && /home/user/biodynamo/third_party/gcc/bin/g++  -I/home/user/biodynamo/build/build-third-party/build_root/math/fftw/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/unix/../clib/res -I/home/user/biodynamo/build/build-third-party/build_root/core/unix/inc -I/home/user/biodynamo/build/build-third-party/build_root/builtins/zstd -I/home/user/biodynamo/build/build-third-party/build_root/core/zstd/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/lz4/inc -I/home/user/biodynamo/build/build-third-party/build_root/obj/include -I/home/user/biodynamo/build/build-third-party/build_root/core/lzma/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/zip/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/thread/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/textinput/src -I/home/user/biodynamo/build/build-third-party/build_root/core/textinput/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/rint/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/meta/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/gui/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/foundation/res -I/home/user/biodynamo/build/build-third-party/build_root/core/foundation/v7/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/foundation/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/cont/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/clingutils/res -I/home/user/biodynamo/build/build-third-party/build_root/core/clingutils/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/clib/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/base/v7/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/base/inc -I/home/user/biodynamo/build/build-third-party/build_root/obj/ginclude -I/home/user/biodynamo/build/build-third-party/build_root/math/mathcore/v7/inc -I/home/user/biodynamo/build/build-third-party/build_root/math/mathcore/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/imt/inc -I/home/user/biodynamo/build/build-third-party/build_root/core/multiproc/inc -I/home/user/biodynamo/build/build-third-party/build_root/net/net/inc -I/home/user/biodynamo/build/build-third-party/build_root/io/io/v7/inc -I/home/user/biodynamo/build/build-third-party/build_root/io/io/inc -std=c++17 -Wno-implicit-fallthrough -Wno-noexcept-type -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -O3 -DNDEBUG -fPIC -std=c++17 -o CMakeFiles/FFTW.dir/src/TFFTRealComplex.cxx.o -c /home/user/biodynamo/build/build-third-party/build_root/math/fftw/src/TFFTRealComplex.cxx
gmake[2]: Leaving directory '/home/user/biodynamo/build/build-third-party/build_root/obj'
gmake[2]: *** No rule to make target 'lib/libfftw3.a', needed by 'lib/libFFTW.so'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:37400: math/fftw/CMakeFiles/FFTW.dir/all] Error 2
gmake[1]: Leaving directory '/home/user/biodynamo/build/build-third-party/build_root/obj'
gmake: *** [Makefile:174: all] Error 2

**Comment by bellenot** [comment]
OK, thanks. But I don't see what could be the issue...

**Comment by ferdymercury** [comment]
Maybe related: https://github.com/microhh/microhh/issues/39

**Comment by LukasBreitwieser** [comment]
Hi @johnpapad24,
Is there a specific reason why you need OpenSUSE in particular? 
From your screenshots I see that you are running in a VM.
ROOT provides binaries for multiple Ubuntu and Alma versions that you could try out
https://root.cern/install/all_releases/

**Comment by dpiparo** [comment]
Waiting for input.
