### ISSUE TITLE
Build Fails on MacOS (ARM, 15)

### ISSUE THREAD

**Issue by cjones051073** [root-project/root#19327]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

I am attempting to update the MacPorts build of root6 to the latest 6.36.02 release.

ROOT versions based on 6.34.X all build and run just fine.

Build fails with

```
Referenced from: <D677D28C-58A1-3164-A2D0-C88FCD9877C8> /opt/local/var/macports/build/root4Ivhdw/work/build/bin/rootcling
  Reason: tried: '/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/opt/local/lib/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libRIO.6.36.so' (no such file), '/opt/local/var/macports/build/root4Ivhdw/work/build/bin/libRIO.6.36.so' (no such file), '/opt/local/var/macports/build/root4Ivhdw/work/build/bin/../lib/root/libRIO.6.36.so' (no such file), '/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/opt/local/lib/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libRIO.6.36.so' (no such file), '/opt/local/var/macports/build/root4Ivhdw/work/build/bin/libRIO.6.36.so' (no such file), '/opt/local/var/macports/build/root4Ivhdw/work/build/bin/../lib/root/libRIO.6.36.so' (no such file)
```

Configuration used is

```
Executing:  cd "/opt/local/var/macports/build/root4Ivhdw/work/build" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makef
iles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_
SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER_LAUNCHER=/opt/local/bin/ccache -DCMAKE_CXX_COMPILER_LAUNCHER=/op
t/local/bin/ccache -DCMAKE_Fortran_COMPILER_LAUNCHER=/opt/local/bin/ccache -DCMAKE_OBJC_COMPILER_LAUNCHER=/opt/local/bin
/ccache -DCMAKE_OBJCXX_COMPILER_LAUNCHER=/opt/local/bin/ccache -DCMAKE_ISPC_COMPILER_LAUNCHER=/opt/local/bin/ccache -DCM
AKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_OBJC_COMPILER="$CC" -DCMAKE_OBJCXX_COMPILER="$CXX" -DCMAKE_POLI
CY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_
FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/loca
l/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DC
MAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -Dgnuinstall=ON -Drpath=ON -DCMAKE_INSTALL_PREFIX="/opt/local/libexec/root6
" -DCMAKE_INSTALL_SYSCONFDIR="/opt/local/libexec/root6/etc/root" -DCMAKE_INSTALL_NAME_DIR="/opt/local/libexec/root6/lib/
root" -Dfortran=ON -Dbuiltin_davix=OFF -Dbuiltin_freetype=ON -Dbuiltin_glew=ON -Dbuiltin_pcre=OFF -Dbuiltin_zlib=OFF -Db
uiltin_lzma=OFF -Dbuiltin_tbb=OFF -Ddavix=ON -Dfftw3=OFF -Dkrb5=OFF -Dmysql=OFF -Dsqlite=OFF -Dodbc=OFF -Dopengl=ON -Dpy
thia6=OFF -Dpythia8=OFF -Droofit=ON -Dssl=ON -Dxml=ON -Dpyroot=ON -Dfitsio=OFF -Dpgsql=OFF -Ddcache=OFF -Dchirp=OFF -Dhd
fs=OFF -Druby=OFF -Dtmva=ON -Dqt=OFF -Dqtgsi=OFF -Dgviz=ON -Dsoversion=ON -Dcxx14=OFF -Dlibcxx=ON -Dxrootd=ON -Dbuiltin_
ftgl=ON -Dbuiltin_gsl=ON -Dmathmore=ON -Dgenvector=ON -Dunuran=ON -Dgdml=ON -Dhttp=ON -Dvc=OFF -Dastiff=ON -Dgeocad=OFF 
-Dr=OFF -Droot7=ON -Dwebgui=ON -Dbuiltin_veccore=OFF -DPNG_LIBRARY=/opt/local/lib/libpng.dylib -DPNG_PNG_INCLUDE_DIR=/op
t/local/include -Druntime_cxxmodules=OFF -DPYTHON_INCLUDE_DIR="/opt/local/Library/Frameworks/Python.framework/Versions/3
.13/Headers" -DPYTHON_EXECUTABLE="/opt/local/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" -DPYTHON_
LIBRARY="/opt/local/Library/Frameworks/Python.framework/Versions/3.13/lib/libpython3.13.dylib" -DXROOTD_INCLUDE_DIR="/op
t/local/include/xrootd" -DGRAPHVIZ_INCLUDE_DIR="/opt/local/include" -DLIBXML2_INCLUDE_DIR="/opt/local/include/libxml2" -
DLIBXML2_LIBRARIES="/opt/local/lib/libxml2.dylib" -DLIBXML2_LIBRARY="/opt/local/lib/libxml2.dylib" -DLIBXML2_XMLLINT_EXE
CUTABLE="/opt/local/bin/xmllint" -Dcocoa=ON -Dx11=OFF -DOPENSSL_ROOT_DIR=/opt/local/libexec/openssl3 -DOPENSSL_INCLUDE_D
IR=/opt/local/libexec/openssl3/include -DWITH_SSL=/opt/local/libexec/openssl3 -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_
CXX_STANDARD=17 -DCMAKE_OSX_DEPLOYMENT_TARGET="15.0" -DCMAKE_OSX_SYSROOT="/Library/Developer/CommandLineTools/SDKs/MacOS
X.sdk" /opt/local/var/macports/build/root4Ivhdw/work/root-6-36-02 
``` 

Full configure and build logs are attached

[build.log.gz](https://github.com/user-attachments/files/21159853/build.log.gz)

[configure.log.gz](https://github.com/user-attachments/files/21159870/configure.log.gz)

### Reproducer

Build within macports build system.

### ROOT version

6.36.02

### Installation method

build from source within MacPorts build system

### Operating system

MacOS 15 (ARM)

**Comment by cjones051073** [comment]
FWIW, if I had to bet I would say the issue is perhaps related to the use of these options to get a proper 'system' installation, which is mandatory for the MacPorts build

```
-Dgnuinstall=ON -Drpath=ON
```

( Historically, I know that the use of -Dgnuinstall=ON has not be particularly well tested by ROOT in the past. )

**Comment by cjones051073** [comment]
Looking a bit into where `rootcling` attempts to locate `libRIO.6.36.so` via @rpath the only paths searched where it could work are those looking into the build area `/opt/local/var/macports/build/root4Ivhdw/work/build` - All the others that look into `/opt/local/lib` will never work *during* the builds as these areas are only populated after the final DESTROOT installation.

Checking rootcling I see

```
Larissa /opt/local/var/macports/build/root4Ivhdw/work/build > otool -L ./bin/rootcling   
./bin/rootcling:
	@rpath/libRIO.6.36.so (compatibility version 6.36.0, current version 6.36.2)
	@rpath/libCling.6.36.so (compatibility version 6.36.0, current version 6.36.2)
	@rpath/libRint.6.36.so (compatibility version 6.36.0, current version 6.36.2)
	@rpath/libThread.6.36.so (compatibility version 6.36.0, current version 6.36.2)
	@rpath/libCore.6.36.so (compatibility version 6.36.0, current version 6.36.2)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1900.180.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1351.0.0)
```

and

```
Larissa /opt/local/var/macports/build/root4Ivhdw/work/build > otool -l ./bin/rootcling 
<snip>
Load command 20
          cmd LC_RPATH
      cmdsize 40
         path /opt/local/lib/libgcc (offset 12)
Load command 21
          cmd LC_RPATH
      cmdsize 32
         path /opt/local/lib (offset 12)
Load command 22
          cmd LC_RPATH
      cmdsize 32
         path @loader_path (offset 12)
Load command 23
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/../lib/root (offset 12)
<snip>
```

and searching the build area for where `libRIO.6.36.so` actually is

```
Larissa /opt/local/var/macports/build/root4Ivhdw/work/build > find . -name libRIO.6.36.so
./lib/libRIO.6.36.so
```

So the problem appears to be otool is set to look for this only under these two locations

```
/opt/local/var/macports/build/root4Ivhdw/work/build/bin/libRIO.6.36.so
/opt/local/var/macports/build/root4Ivhdw/work/build/bin/../lib/root/libRIO.6.36.so
```

neither of which matches where it actually is

```
/opt/local/var/macports/build/root4Ivhdw/work/build/lib/libRIO.6.36.so
```

**Comment by cjones051073** [comment]
Disabling rpath made no difference `-Drpath=OFF` - build still fails in a similar way

```
dyld[9421]: Library not loaded: @rpath/libRIO.6.36.so
  Referenced from: <0AC7BD1B-55E7-3C44-B68D-B060DB0280FB> /opt/local/var/macports/build/rootEDarvc/work/build/bin/rootcling
  Reason: tried: '/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/opt/local/lib/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libRIO.6.36.so' (no such file), '/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/opt/local/lib/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libRIO.6.36.so' (no such file)
```

**Comment by hageboeck** [comment]
Hello,
thanks for the analysis! I agree that it's an RPath problem. Since it wasn't seen before 6.36 got released, it's likely related to `gnuinstall`, so we will investigate this next week.

**Comment by cjones051073** [comment]
TBH It would be nice if the `gnuinstall` option was better tested than it currently is. I have ran into problems with this in the past. Its pretty essential to package managers like MacPorts, or Homebrew to name just two to use this as we require a regular normal installation.

**Comment by hageboeck** [comment]
> TBH It would be nice if the `gnuinstall` option was better tested than it currently is. I have ran into problems with this in the past. Its pretty essential to package managers like MacPorts, or Homebrew to name just two to use this as we require a regular normal installation.

I fully agree! I'm already investigating to put it in the nightlies. On master, I already had a green build, but I'm moving to 6.36 now.

**Comment by ferdymercury** [comment]
Related: https://its.cern.ch/jira/browse/ROOT-9758

**Comment by cjones051073** [comment]
Any news ? The failure of the gnu install option is preventing my updating the MacPorts version to the 6.36 series of releases.

**Comment by hageboeck** [comment]
> Any news ? The failure of the gnu install option is preventing my updating the MacPorts version to the 6.36 series of releases.

So far I can only say that I didn't manage to reproduce on an Intel Mac. I'll run a test using the CI machines now.

**Comment by cjones051073** [comment]
Are you using the same configure options as I posted above. Most likely don't matter but some might.

I am also on an ARM of course.

**Comment by cjones051073** [comment]
these in particular

```
 -Wno-dev -Dgnuinstall=ON -Drpath=ON -DCMAKE_INSTALL_PREFIX="/opt/local/libexec/root6
 -DCMAKE_INSTALL_SYSCONFDIR="/opt/local/libexec/root6/etc/root" 
-DCMAKE_INSTALL_NAME_DIR="/opt/local/libexec/root6/lib/root"
```

**Comment by cjones051073** [comment]
It might be easy to scan the list we use looking at

https://github.com/macports/macports-ports/blob/master/science/root6/Portfile#L114

Could any of the options we use there be the problem. As I said before, what's there has been working just for for a long while now for previous root6 releases, this issue is new to 6.36.X

**Comment by hageboeck** [comment]
> Are you using the same configure options as I posted above. Most likely don't matter but some might.
> 
> I am also on an ARM of course.

Many won't matter, indeed, but some will. Since I didn't have arm, I tried in the ROOT CI [link for project members](https://github.com/root-project/root/actions/runs/16446692866/job/46480513245?pr=19435). I managed to provoke a similar error, and interestingly also on Linux! 🙂
It's not the same you see, but it's for sure rpath:
```
Error in <UnknownClass::FindDynamicLibrary>: libRIO[.so | .dll | .dylib | .sl | .dl | .a] does not exist in .:/usr/local/lib/root:/usr/local/lib:/usr/X11R6/lib:/usr/lib:/lib:/lib/x86_64-linux-gnu:/usr/local/lib64:/usr/lib64:/lib64:
```
I will build a local example on Linux again to see what can be done about it.

**Comment by cjones051073** [comment]
Thanks for taking the time to investigate and eventually reproduce. Please let me know if I can help test patches etc. ?

**Comment by hageboeck** [comment]
OK, here is what I tried so far:
- On Linux, gnuinstall comes out OK
- A "manual" build on Mac15, Arm was also OK. I pretty much copied the config from the portfile you linked:
  > `https://github.com/macports/macports-ports/blob/master/science/root6/Portfile#L114`
- Switching two of the CI builders to `gnuinstall` on master provoked only a single test failure, but not the situation you describe. The build completes OK.

However, I don't think I should install macports on ROOT's CI machines, so it's going to be tricky to reproduce it exactly. I will look up if I can add an rpath "manually", which you could test.

**Comment by hageboeck** [comment]
Hello @cjones051073, I think I found it!

From your post:
> `-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib"`

And work on the install rpath probably broke your workflow https://github.com/root-project/root/issues/19134.

Here is how I understand it currently:
- Would it be possible not to build with install rpath? The build *should* be able to complete with the RPaths that CMake sets automatically. If it's not possible, we would have to fix up the install RPaths with paths that have nothing to do with the installed locations, so we would pollute the RPath variables with broken paths.
- When installing, the RPaths currently get overwritten with `<what you provide as CMAKE_INSTALL_RPATH> @loader_path @loader_path/../lib/root`.
  - The first item is under your control. What you set will get used. I'm not sure you need to set anything, though, since the next two items should cover all cases I can think of.
  - The second item would work for finding libs from libs (same directory), wherever they are installed.
  - The third item is an attempt at navigating from `bin/` to the "lib/" directory, and it's using `CMAKE_INSTALL_FULL_xxx`. That is, it figures out how to go from `${CMAKE_INSTALL_PREFIX}/bin` to `${CMAKE_INSTALL_PREFIX}/lib/root` if `gnuinstall=ON` (with `gnuinstall=OFF`, it's just `..PREFIX}/lib`). For the installed ROOT, this looks OK, doesn't it? For the build tree, that's not correct, though, and that's why `rootcling` fails for you.

Therefore, could you let me know if
```diff
- -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib"
+ -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=OFF
```
Gets you to a working installation?

**Comment by cjones051073** [comment]
We need to enable rpath for other reasons, so disabling it is not really a good option for us.

**Comment by cjones051073** [comment]
What if we keep  `-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON` but remove `-DCMAKE_INSTALL_RPATH="/opt/local/lib"` ? What will happen then ?

**Comment by hageboeck** [comment]
> We need to enable rpath for other reasons, so disabling it is not really a good option for us.

In case there was a misunderstanding, I didn't mean to switch off RPath completely. What I meant is to use the automatic build rpath that CMake figures out when you configure ROOT, i.e. `Drpath=On -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=OFF`. This would result in an RPath sufficient to move from `bin/` to `lib/` at build time, and external finds would also be added to that RPath.
Later, when you install, this would get rewritten to `CMAKE_INSTALL_RPATH` + lib --> lib + bin --> lib`.

If you absolutely need to keep building with install RPath, you could try:
```
-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="@loader_path/../lib"
```
which would probably install with:
`@loader_path/../lib @loader_path @loader_path/../lib/root`
The first entry seems unnecessary, and it has precedence, but maybe it doesn't do any harm.

**Comment by cjones051073** [comment]
I see. Then I would suggest the option `-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=OFF` is a bit misleading if rpath is still used..

If I just remove `-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib"` but don't add the OFF option, so rely on the root defaults, would that work ?

**Comment by jezwilkinson** [comment]
FWIW: the other issue that was just mentioned (similar-looking RPath issues in ROOT MacOS installed via the Spack package manager) was resolved by changing the `CMAKE_INSTALL_RPATH` to not match any of the paths from build time loaded by `CMAKE_INSTALL_RPATH_USE_LINK_PATH`: (see https://github.com/spack/spack-packages/issues/215 and https://github.com/spack/spack-packages/pull/436)

In that case the problem was that `install_name_tool` was refusing to add the `@loader_path` paths if there were any clashes between the `INSTALL_RPATH` and what was already present at build time - though I don't know if that's exactly the same as what you're seeing here, since `otool` is referencing the `@loader_path` paths for you.

**Comment by hageboeck** [comment]
> I see. Then I would suggest the option `-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=OFF` is a bit misleading if rpath is still used..
> 
> If I just remove `-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib"` but don't add the OFF option, so rely on the root defaults, would that work ?

Yes, I believe this would work. These are all CMake variables in the end, so it goes to CMake defaults, which is to use a CMake-generated RPath at build time, and later relocate to the install RPath. Even if you find the switch misleading, that's what CMake gives to us. 🙂

**Comment by guitargeek** [comment]
Hello! I have opened a PR for the 6.36 branch that should fix the rpath issues from the ROOT side:

 * https://github.com/root-project/root/pull/19518

It is taken from this PR which was merged to ROOT master:

  * https://github.com/root-project/root/pull/19501

Now, ROOT is not messing around with CMake variables like `CMAKE_INSTALL_RPATH` anymore, and also not with that variable in the CMake cache. It is simply appending to the `rpath` of the ROOT libraries and executables.

If there are still problems related to the runpaths after merging that PR, it's very likely that these are related more to your MacPorts configuration. If you are convinced that there is still an issue on the ROOT side, please feel free to re-open this issue and create a new one! Thanks.

**Comment by cjones051073** [comment]
> Hello! I have opened a PR for the 6.36 branch that should fix the rpath issues from the ROOT side:
> 
> * [[v636][CMake] Set `rpath` for individual targets and not globally #19518](https://github.com/root-project/root/pull/19518)
> 
> It is taken from this PR which was merged to ROOT master:
> 
> * [[CMake] Set `rpath` for individual targets and not globally #19501](https://github.com/root-project/root/pull/19501)
> 
> Now, ROOT is not messing around with CMake variables like `CMAKE_INSTALL_RPATH` anymore, and also not with that variable in the CMake cache. It is simply appending to the `rpath` of the ROOT libraries and executables.
> 
> If there are still problems related to the runpaths after merging that PR, it's very likely that these are related more to your MacPorts configuration. If you are convinced that there is still an issue on the ROOT side, please feel free to re-open this issue and create a new one! Thanks.

@guitargeek I have just tried the new 6.36.04 release and nothing has changed for me, the build still fails in the very same way, using a build configuration that is perfectly fine for 6.34.X. It might well be triggered by something on the MacPorts side, so option we use, but I maintain there is still an issue on the root side here. See attached log.

[root6.36.build-error.log](https://github.com/user-attachments/files/21986149/root6.36.build-error.log)

**Comment by cjones051073** [comment]
```
 Referenced from: <E1A17F5A-9228-3AB6-9D34-6EA7D65D2C99> /opt/local/var/macports/build/root6-317f8c0f/work/build/bin/rootcling
  Reason: tried: '/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/opt/local/lib/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libRIO.6.36.so' (no such file), '/opt/local/var/macports/build/root6-317f8c0f/work/build/bin/../lib/root/libRIO.6.36.so' (no such file), '/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libgcc/libRIO.6.36.so' (no such file), '/opt/local/lib/libRIO.6.36.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libRIO.6.36.so' (no such file), '/opt/local/var/macports/build/root6-317f8c0f/work/build/bin/../lib/root/libRIO.6.36.so' (no such file)
```

The last file there is the closest to correct. Its trying 

```
'/opt/local/var/macports/build/root6-317f8c0f/work/build/bin/../lib/root/libRIO.6.36.so'
```

whereas the file that actually exists is

```
'/opt/local/var/macports/build/root6-317f8c0f/work/build/bin/../lib/libRIO.6.36.so'
```

why is that incorrect `root/` directory being added there ?

**Comment by guitargeek** [comment]
Hi! That is expected. 6.36.04 was a patch release, and my improvements to the build system were not backported, because there was no feedback from your side after https://github.com/root-project/root/issues/19327#issuecomment-3150431641 if the problem was actually fixed in ROOT `master`. And we don't backport patches that were not confirmed to fix the original reported problem.

Sorry, it's my fault for not explicitly asking you if things work with ROOT `master` now! Maybe you can give it a try? So we know if things will work with the upcoming release or if more work is required. The next non-patch release, 6.38.00 is due in November by the way.

**Comment by cjones051073** [comment]
> Hi! That is expected. 6.36.04 was a patch release, and my improvements to the build system were not backported, because there was no feedback from your side after [#19327 (comment)](https://github.com/root-project/root/issues/19327#issuecomment-3150431641) if the problem was actually fixed in ROOT `master`. And we don't backport patches that were not confirmed to fix the original reported problem.
> 
> Sorry, it's my fault for not explicitly asking you if things work with ROOT `master` now! Maybe you can give it a try? So we know if things will work with the upcoming release or if more work is required. The next non-patch release, 6.38.00 is due in November by the way.

I'm confused, I thought this PR

https://github.com/root-project/root/pull/19518

was targeting the 6.36 branch, and the release notes for 6.36.04 explicitly mention this issue !

https://root.cern/doc/v636/release-notes.html#release-6.36.04

You said yourself in the post I replied to "I have opened a PR for the 6.36 branch that should fix the rpath issues from the ROOT side:" - I fail to see how I could read anything other than it should be fixed in the 6.36 branch, for the next release from that, and the release notes seem to confirm this. This is in fact what I was waiting for, to test. Building a master branch version is posible but not so easy and for sure not something I can deploy within MacPorts so its not really a route I was looking to go.

**Comment by guitargeek** [comment]
Oh... You're right, I remembered the whole thing wrong! I thought I didn't do the backport. Ok, then this problem is unexpected. Let me reopen the issue and think about it.

**Comment by guitargeek** [comment]
Sorry that this problem still persists! I see there are still some problems with the library path for `rootcling`. I have opened a PR to fix them:

  * https://github.com/root-project/root/pull/19750

Could you check if it works with these changes that I suggest? Like this, we're sure that the next release will work 😆 

Thanks for your patience!
