### ISSUE TITLE
PyROOT in root 6.24 branch hangs while loading CMSSW library

### ISSUE THREAD

**Issue by smuzaffar** [root-project/root#7718]
Hi,
  We are trying to update root 6.24 branch (commit https://github.com/root-project/root/commit/7c0cfaca4c70c7394328547c05e00028b0079a03)  in CMSSW special integration builds (https://github.com/cms-sw/cmsdist/pull/6746/files ) but looks like pyROOT fails/hangs for some special dictionaries. 

While building cmssw , we use https://github.com/cms-sw/cmssw/blob/master/FWCore/Utilities/scripts/edmCheckClassVersion to check for root dictionaries class versions. This works for most of our dictionaries e.g following two run fine ( https://github.com/cms-sw/cmssw/blob/master/DataFormats/TauReco/src/classes_def_hlt.xml, https://github.com/cms-sw/cmssw/blob/master/DataFormats/TauReco/src/classes_def_1.xml )
```
> src/FWCore/Utilities/scripts/edmCheckClassVersion -l libDataFormatsTauReco.so -x src/DataFormats/TauReco/src/classes_def_hlt.xml
> src/FWCore/Utilities/scripts/edmCheckClassVersion -l libDataFormatsTauReco.so -x src/DataFormats/TauReco/src/classes_def_1.xml
```
but it fails/hangs for https://github.com/cms-sw/cmssw/blob/master/DataFormats/TauReco/src/classes_def_2.xml
```
> src/FWCore/Utilities/scripts/edmCheckClassVersion -l libDataFormatsTauReco.so -x src/DataFormats/TauReco/src/classes_def_2.xml
```
Most of the times the above command just hangs with error https://muzaffar.web.cern.ch/root624/err1.log but once I was able to get this error https://muzaffar.web.cern.ch/root624/err.log . Can you please look in to it and see if this log helps? 

In case you want to try it yourself then you go to cmsdev25 and do
```
>cd /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100
>cmsenv
>/build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/src/FWCore/Utilities/scripts/edmCheckClassVersion -l libDataFormatsTauReco.so -x /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/src/DataFormats/TauReco/src/classes_def_2.xml
```

FYI @mrodozov  @makortel @Dr15Jones

**Comment by smuzaffar** [comment]
the root commit b802a6b was working fine. So the changes which we are testing are  https://github.com/root-project/root/compare/b802a6b...7c0cfac

**Comment by Axel-Naumann** [comment]
Would you be able to provide me with a valgrind report? `--num-callers=50 --track-origins=yes --suppressions=$ROOTSYS/etc/valgrind-root.supp` would help a lot.

**Comment by Axel-Naumann** [comment]
This might be a dupe of https://github.com/root-project/root/issues/7657 - but I'd like to make progress with both of them independently to not serialize progress towards v6.24/00!

**Comment by smuzaffar** [comment]
@Axel-Naumann , valgrind also hangs without printing nay usefull information. Under gdb I see this [a]. If I build `root` in Debug mode then I do not get this segmentation fault.
[a]
```
(gdb) where
#0  0x00007ffff6f5d272 in _int_malloc () from /lib64/libc.so.6
#1  0x00007ffff6f6078c in malloc () from /lib64/libc.so.6
#2  0x00007ffff67ad7c5 in operator new (sz=127) at ../../../../libstdc++-v3/libsupc++/new_op.cc:50
#3  0x00007ffff683fc6d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate (this=this@entry=0x7fffffff38c0, __pos=63, __len1=__len1@entry=0,
    __s=0x7ffff471c3cb "::", __len2=2)
    at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre6-slc7_amd64_gcc900/build/CMSSW_11_1_0_pre6-build/BUILD/slc7_amd64_gcc900/external/gcc/9.3.0/gcc-9.3.0/obj/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h:993
#4  0x00007ffff684127b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append (this=0x7fffffff38c0, __s=<optimized out>, __n=<optimized out>)
    at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre6-slc7_amd64_gcc900/build/CMSSW_11_1_0_pre6-build/BUILD/slc7_amd64_gcc900/external/gcc/9.3.0/gcc-9.3.0/obj/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/char_traits.h:300
#5  0x00007ffff199d41f in cling::LookupHelper::findScope(llvm::StringRef, cling::LookupHelper::DiagSetting, clang::Type const**, bool) const ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCling.so
#6  0x00007ffff19237ef in TClingClassInfo::TClingClassInfo(cling::Interpreter*, char const*, bool) ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCling.so
#7  0x00007ffff189c644 in TCling::GetInterpreterTypeName(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool) ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCling.so
#8  0x00007ffff6b7745a in TClass::GetClass(char const*, bool, bool, unsigned long, unsigned long) ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCore.so
#9  0x00007ffff6b9f27b in TProtoClass::FillTClass(TClass*) ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCore.so
#10 0x00007ffff6b80bea in TClass::Init(char const*, short, std::type_info const*, TVirtualIsAProxy*, char const*, char const*, int, int, ClassInfo_t*, bool) ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCore.so
#11 0x00007ffff6b821c2 in TClass::TClass(char const*, short, std::type_info const&, TVirtualIsAProxy*, char const*, char const*, int, int, bool) ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCore.so
#12 0x00007ffff6b826d9 in ROOT::CreateClass(char const*, short, std::type_info const&, TVirtualIsAProxy*, char const*, char const*, int, int) ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCore.so
#13 0x00007ffff6b918ea in ROOT::TGenericClassInfo::GetClass() ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCore.so
#14 0x00007ffff6b76fea in TClass::GetClass(char const*, bool, bool, unsigned long, unsigned long) ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCore.so
#15 0x00007fffdedbc05b in ?? ()
#16 0x000000000000042e in ?? ()
#17 0x0000000006c6f350 in ?? ()
#18 0x0000000006d34680 in ?? ()
#19 0x0000000006c76630 in ?? ()
#20 0x0000000006c764c0 in ?? ()
#21 0x0000000006c6f350 in ?? ()
#22 0x0000000006c76630 in ?? ()
#23 0x00007fffffff42a8 in ?? ()
#24 0x00000000057251f0 in ?? ()
#25 0x00007ffff6b777d0 in ?? ()
   from /build/muz/r624/w/tmp/BUILDROOT/ea8220342d406ab7dbc2d210a1e9351b/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_ROOT624_X_2021-03-25-1100/external/slc7_amd64_gcc900/lib/libCore.so
#26 0x00007fffffff42a8 in ?? ()
#27 0x00007fffffff4220 in ?? ()
#28 0x0000000100000000 in ?? ()
#29 0x0000000000000000 in ?? ()
```

**Comment by smuzaffar** [comment]
The call to `ROOT.TClass.GetClass(name)` https://github.com/cms-sw/cmssw/blob/master/FWCore/Utilities/scripts/edmCheckClassVersion#L129 failed for class `reco::PFTau`  https://github.com/cms-sw/cmssw/blob/master/DataFormats/TauReco/interface/PFTau.h

**Comment by Axel-Naumann** [comment]
> In case you want to try it yourself then you go to cmsdev25

Help! @pcanal maybe? What I'm after, given the backtrace of https://github.com/root-project/root/issues/7718#issuecomment-809942210 , is which frames cause the inf loop, i.e. which is the frame that doesn't return.

@smuzaffar what we can also try, because of the "only happens in release builds", is https://github.com/root-project/root/pull/7752

**Comment by smuzaffar** [comment]
@Axel-Naumann , do you have  #7752 equivalent for v6.24 branch?

**Comment by Axel-Naumann** [comment]
That's https://github.com/root-project/root/pull/7767

**Comment by smuzaffar** [comment]
thanks, I am testing these now 
- v6.24 https://github.com/cms-sw/root/pull/153
- master https://github.com/cms-sw/root/pull/152

**Comment by smuzaffar** [comment]
@Axel-Naumann , looks like some latest development in v6.24 branch has fixed the hanging issue. I have tested https://github.com/root-project/root/commit/126c9c8627560f1169d60634aaf4d733568c8ccc (without #7767) and this time cmssw build was successful. We get runtime errors now, see the details here https://github.com/cms-sw/cmsdist/pull/6777#issuecomment-811478743 . You can find the crash log https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a7de73/13897/runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS/step3_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS.log.

With your changes in  #7767 ( on top of https://github.com/root-project/root/commit/126c9c8627560f1169d60634aaf4d733568c8ccc ) , things look in much better state. PR tests ( https://github.com/cms-sw/root/pull/153#issuecomment-811570082 ) show no build or run time errors. But we do see some comparison differences for our reconstruction code.

**Comment by smuzaffar** [comment]
ROOT master based CMSSW releases also show the same resulsts:
- https://github.com/cms-sw/cmsdist/pull/6778#issuecomment-811474459 without  #7752 . There is no hanging at build time but we see runtime crashes (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-46d8cb/13898/runTheMatrix-results/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVDSIPIXELCALRUN1+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step3_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVDSIPIXELCALRUN1+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5.log)
- https://github.com/cms-sw/root/pull/152#issuecomment-811584967 with #7752 . No build or runtime errors but there are comparison differences.

**Comment by Axel-Naumann** [comment]
Thank you, @smuzaffar ! Am I reading this correctly that it's currently unknown whether the comparison differences are introduced by #7752 or were pre-existing?

**Comment by smuzaffar** [comment]
These differences were not there when last time we updated to v6.24 branch commit b802a6b (see https://github.com/cms-sw/cmsdist/pull/6730#issuecomment-799704333 and https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-03-14-2300+963134/41710/validateJR.html ). 

I could be that some of latest cmssw changes might have caused these differences, I am re-running the tests based on  latest cmssw release now

**Comment by Axel-Naumann** [comment]
Thanks. To make progress towards v6.24 I will merge https://github.com/root-project/root/pull/7752 and https://github.com/root-project/root/pull/7767 - IIUC they improve the situation also for CMS (they do for ATLAS). I hope that this does not complicate finding the source of the comparison failure.

**Comment by smuzaffar** [comment]
@Axel-Naumann , based on latest cmssw ROOT624 IB, the comparison results look good now https://github.com/cms-sw/root/pull/153#issuecomment-811941178 .

**Comment by Axel-Naumann** [comment]
Phew, thanks, @smuzaffar But I have bad news: I needed to revisit the PR #7752 / #7767 . I will have to ask for your favor to test another PR replacing those, sorry about that! (But at least we now know what the baseline is - the comparison is good!) I'll be back...

**Comment by smuzaffar** [comment]
no problem, just ping me when you have something to test @Axel-Naumann

**Comment by Axel-Naumann** [comment]
I now have the following:
- master: https://github.com/root-project/root/pull/7773
- v6-24: https://github.com/root-project/root/pull/7780

Could you let me know whether that *also* solves the issues you saw? Any one of them is enough. Thank you, @smuzaffar !

**Comment by smuzaffar** [comment]
I am testing these now
- master : https://github.com/cms-sw/root/pull/154
- v6-24: https://github.com/cms-sw/root/pull/155

**Comment by smuzaffar** [comment]
@Axel-Naumann , v6.24 fix looks good for CMS . All tests passed https://github.com/cms-sw/root/pull/155#issuecomment-812869144

**Comment by Axel-Naumann** [comment]
Thanks you, @smuzaffar ! Now fixed in master and v6-24-00-patches.

**Comment by smuzaffar** [comment]
@Axel-Naumann ,  root v.6.24 branch is still broken for us. Test root commit 0ae9f99 generated multiple runtime errors [a] for us. @makortel @Dr15Jones is it something CMSSW related or root is causing this ?
Testign eda45838695204139e372d712b1d72c9d5370160 + https://github.com/cms-sw/root/pull/155/files looks good though [b] . Only difference is the addition commit https://github.com/root-project/root/commit/3480394c02a6335d271f95fcf160274811091155 , do you thing this update might be causing these crashes?

[a] https://github.com/cms-sw/cmsdist/pull/6787#issuecomment-814302828
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-efd635/14020/addOnTests/pat1/cmsRun__data_cmsbld_jenkins_workspace_ib-run-pr-addon_CMSSW_11_3_ROOT624_X_2021-04-05-2300_src_PhysicsTools_PatAlgos_test_IntegrationTest_cfg.py.log

```
cmsRun: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_3_ROOT624_X_2021-04-05-2300/src/FWCore/Concurrency/src/WaitingTaskList.cc:57: void edm::WaitingTaskList::reset(): Assertion `m_head == nullptr' failed.

```

[b] https://github.com/cms-sw/root/pull/155#issuecomment-812869144

**Comment by Dr15Jones** [comment]
@smuzaffar the failure is during 1 thread. Even though the failure is in CMSSW this shouldn't ever happen for 1 thread alone. So it seems like ROOT is doing something to cause a problem.

**Comment by Dr15Jones** [comment]
So the problem happens at end Lumi so my guess is we had an exception and the system is trying to shut down and a task didn't run when it should have. So if I'm correct, then there would be a problem in CMSSW with not properly handling an exception. BUT it also means ROOT is now throwing an exception we can't handle.

**Comment by smuzaffar** [comment]
Looks like  3480394 commit is causing the issue. I re-ran with eda4583 + https://github.com/cms-sw/root/pull/155/files ( i.e. root v6-24 patches branch without  3480394  ) and all tests passed https://github.com/cms-sw/root/pull/155#issuecomment-814408255

**Comment by pcanal** [comment]
@smuzaffar Do you have a non-EOS reproducer?

**Comment by smuzaffar** [comment]
no @pcanal , looks like all of the failed one are read data from EOS. There are few unit tests which fails with different errors [a] 

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-efd635/14020/unitTests/failed.html
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-efd635/14020/unitTests/src/TopQuarkAnalysis/TopHitFit/test/runtestTqafTopHitFit/testing.log
```
06-Apr-2021 18:34:49 CEST  Closed file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_9_2_2/RelValProdTTbar_13/AODSIM/91X_mcRun2_asymptotic_v3-v1/10000/EEB99F74-DA4D-E711-A41C-0025905A48F2.root
----- Begin Fatal Exception 06-Apr-2021 18:34:50 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Calling EventProcessor::runToCompletion (which does almost everything after beginJob and before endJob)
Exception Message:
A std::exception was thrown.
vector::_M_fill_insert
----- End Fatal Exception -------------------------------------------------
```

**Comment by smuzaffar** [comment]
@pcanal , I am trying to test latest root v6-22 patches branch and we also get same failures there  https://github.com/cms-sw/cmsdist/pull/6790#issuecomment-814504953

**Comment by smuzaffar** [comment]
@pcanal , you can reproduce the error by doing the following on cmsdev20-25 VMs. This is based on root master (build in debug mode)

```
cd /build/pcanal
/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/6788/14005/install.sh
cd CMSSW_11_3_ROOT6_X_2021-04-05-2300
eval `scram run -sh`
export CMS_PATH=/cvmfs/cms-ib.cern.ch
xrdcp root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_9_2_2/RelValProdTTbar_13/AODSIM/91X_mcRun2_asymptotic_v3-v1/10000/EEB99F74-DA4D-E711-A41C-0025905A48F2.root .
cp $CMSSW_BASE/src/PhysicsTools/PatAlgos/test/IntegrationTest_cfg.py .
sed -i -e "s|= *filesRelValProdTTbarAODSIM|= cms.untracked.vstring('file://$CMSSW_BASE/EEB99F74-DA4D-E711-A41C-0025905A48F2.root')|" IntegrationTest_cfg.py
cmsRun  IntegrationTest_cfg.py

```

**Comment by pcanal** [comment]
@smuzaffar Can you put the file somewhere? I don't have the right certificate to download the file.

**Comment by smuzaffar** [comment]
@pcanal , here it is /afs/cern.ch/user/c/cmsbuild/public/EEB99F74-DA4D-E711-A41C-0025905A48F2.root

**Comment by pcanal** [comment]
@smuzaffar Got it.  thanks.

**Comment by pcanal** [comment]
@smuzaffar I am still doing something odd.  I get:
```
Begin processing the 1st record. Run 1, Event 2, LumiSection 1 on stream 0 at 07-Apr-2021 21:41:09.524 CEST
cmsRun: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_3_ROOT6_X_2021-04-05-2300/src/FWCore/Concurrency/src/WaitingTaskList.cc:57: void edm::WaitingTaskList::reset(): Assertion `m_head == nullptr' failed.

Thread 1 "cmsRun" received signal SIGABRT, Aborted.
0x00007ffff4ae33d7 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff4ae33d7 in raise () from /lib64/libc.so.6
#1  0x00007ffff4ae4ac8 in abort () from /lib64/libc.so.6
#2  0x00007ffff4adc1a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff4adc252 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff7e8fd19 in edm::WaitingTaskList::reset() () from /build/pcanal/CMSSW_11_3_ROOT6_X_2021-04-05-2300/lib/slc7_amd64_gcc900/libFWCoreConcurrency.so
#5  0x00007ffff7ce3cbb in edm::Worker::reset() () from /build/pcanal/CMSSW_11_3_ROOT6_X_2021-04-05-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#6  0x00007ffff7ce2664 in edm::WorkerManager::resetAll() () from /build/pcanal/CMSSW_11_3_ROOT6_X_2021-04-05-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#7  0x00007ffff7be8df0 in edm::StreamSchedule::processOneStreamAsync<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)2> >(edm::WaitingTaskHolder, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)2>::TransitionInfoType&, edm::ServiceToken const&, bool)::{lambda()#2}::operator()() ()
   from /build/pcanal/CMSSW_11_3_ROOT6_X_2021-04-05-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#8  0x00007ffff7be9124 in tbb::internal::function_task<edm::StreamSchedule::processOneStreamAsync<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)2> >(edm::WaitingTaskHolder, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)2>::TransitionInfoType&, edm::ServiceToken const&, bool)::{lambda()#3}>::execute() ()
   from /build/pcanal/CMSSW_11_3_ROOT6_X_2021-04-05-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#9  0x00007ffff5eb026d in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::process_bypass_loop (this=this@entry=0x7ffff1b53200, context_guard=..., t=0x7ffff1b4b240, 
    isolation=isolation@entry=0) at ../../include/tbb/task.h:1003
#10 0x00007ffff5eb0756 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7ffff1b53200, parent=..., child=<optimized out>) at ../../src/tbb/scheduler.h:650
#11 0x00007ffff7bd0cb3 in tbb::internal::task_group_base::wait() () from /build/pcanal/CMSSW_11_3_ROOT6_X_2021-04-05-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#12 0x00007ffff7bc1570 in edm::EventProcessor::endUnfinishedLumi() () from /build/pcanal/CMSSW_11_3_ROOT6_X_2021-04-05-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#13 0x00007ffff7b85ab3 in edm::EventProcessor::runToCompletion() [clone .cold] () from /build/pcanal/CMSSW_11_3_ROOT6_X_2021-04-05-2300/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#14 0x000000000040bae6 in tbb::interface7::internal::delegated_function<main::{lambda()#1}::operator()() const::{lambda()#1} const, void>::operator()() const ()
#15 0x00007ffff5ea9552 in tbb::interface7::internal::task_arena_base::internal_execute (this=0x7fffffff3630, d=...) at ../../src/tbb/arena.cpp:1105
#16 0x000000000040ca13 in main::{lambda()#1}::operator()() const ()
#17 0x000000000040b62c in main ()
```

**Comment by smuzaffar** [comment]
no this is correct. This is one of the errors we get ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-941446/14005/addOnTests/pat1/cmsRun__data_cmsbld_jenkins_workspace_ib-run-pr-addon_CMSSW_11_3_ROOT6_X_2021-04-05-2300_src_PhysicsTools_PatAlgos_test_IntegrationTest_cfg.py.log ) . 

If you are interested in error https://github.com/root-project/root/issues/7718#issuecomment-814425870 then I can provide the reproducer for that too

**Comment by Dr15Jones** [comment]
@pcanal in gdb make sure to do `catch throw` before running.

**Comment by smuzaffar** [comment]
@pcanal , you can run the following to reproduce the error https://github.com/root-project/root/issues/7718#issuecomment-814425870

```
# in cmssw area
cp $CMSSW_BASE/src/TopQuarkAnalysis/TopTools/test/ttJetPartonMatch_cfg.py .
sed -i -e "s|(relValTTbar)|('file:///afs/cern.ch/user/c/cmsbuild/public/EEB99F74-DA4D-E711-A41C-0025905A48F2.root')|" ttJetPartonMatch_cfg.py
cmsRun ttJetPartonMatch_cfg.py
```

**Comment by pcanal** [comment]
>  in gdb make sure to do catch throw before running.

indeed :)

@smuzaffar I want to rebuild ROOT in debug mode.  Which commit and repository was used in that build?

**Comment by smuzaffar** [comment]
For this build, I used https://github.com/cms-sw/root repository with cms/master/be1bae0 branch ( this branch is identical to root-project/root commit be1bae0 ). You should be able to build root from root-project/root branch too, we only add https://github.com/cms-sw/root/commit/b462cf572aebf5c4fa6057ff454b81dd85057b86 patch on top of root master branch

**Comment by mrodozov** [comment]
@pcanal this build /cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/6788/14005/install.sh 
is a Debug build 
https://github.com/cms-sw/cmsdist/pull/6788/files#diff-f7675e8ed13f5b85d8cc2cfa4022ca6ab330c2f057a3c97654a365dbfa721ca5R43
unless you need also the LLVM_BUILD_TYPE to be Debug in which case I'll change it and rebuild

**Comment by pcanal** [comment]
The suspicious commit was reverted for 6.24/00 but will be reintroduce (and fixed :) ) for v6.24/02

**Comment by mrodozov** [comment]
thank you @pcanal  I'm getting it to test it. removed only for 6.24 (or also from master) ?

**Comment by pcanal** [comment]
Only 6.24.

**Comment by pcanal** [comment]
@mrodozov The build seems to have gone away.  Could you give me another one?

**Comment by mrodozov** [comment]
`/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/6787/14310/install.sh`
this is from yesterday

**Comment by pcanal** [comment]
This seems to be using the v6.24 patch rather than the main branch.  This is fine :) but I need to find out the right cmssw/root commit to use in my build, can you remind me which one correspond to that build (and/or how to find out).

**Comment by mrodozov** [comment]
we have also the master, I rebuilt it earlier
/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmsdist/6788/14348/install.sh

**Comment by pcanal** [comment]
Is that still using the 'cms/master/be1bae0 branch ' ?

**Comment by mrodozov** [comment]
yes it's the same

**Comment by mrodozov** [comment]
I removed the commit from master and 6-22 to get the latest changes on master until this is resolved
Removing it fixes the runtime failures in 6-22 and master
This is the gdb run
https://github.com/cms-sw/cmsdist/pull/6841#issuecomment-828556791
We built an IB with with ROOT with debug flag before removing the commit
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_12_0/2021-04-29-2300?selectedArchs=slc7_amd64_gcc900&selectedFlavors=ROOT6_X&selectedStatus=failed
The IB is
CMSSW_12_0_ROOT6_X_2021-04-29-2300

**Comment by pcanal** [comment]
See also #7754

**Comment by hahnjo** [comment]
@pcanal @Axel-Naumann this issue is open, but marked as fixed. Reading https://github.com/root-project/root/issues/7718#issuecomment-818871932, should this maybe also say 6.24/02?

**Comment by osschar** [comment]
https://github.com/root-project/root/commit/3480394c02a6335d271f95fcf160274811091155

@alja and I saw exceptions when reading PFCandiadate vector, the size obtained by the auto-generated code was O(10^20).

We have a relatively slim reproducer on top of FWLite, can dig it out / give access to the machine here at UCSD if relevant.

```
#0  0x00007ffff17ae32e in __cxxabiv1::__cxa_throw (obj=obj@entry=0xf49a880, tinfo=0x7ffff18d4270 <typeinfo for std::length_error>, dest=0x7ffff17c34f0 <std::length_error::~length_error()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:78
#1  0x00007ffff17a4cd4 in std::__throw_length_error (__s=0x7ffff7f98726 "vector::_M_fill_insert") at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:78
#2  0x00007ffff7f758d2 in std::vector<void const*, std::allocator<void const*> >::_M_check_len (this=0x13ff4df8, __n=18446744073692016332, __s=0x7ffff7f98726 "vector::_M_fill_insert") at /data2/alja/fwWeb/cmsBetaBld/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/stl_vector.h:1756
#3  0x00007ffff7f7ab11 in std::vector<void const*, std::allocator<void const*> >::_M_fill_insert (this=0x13ff4df8, __position=..., __n=18446744073692016332, __x=@0x7fffffff9320: 0x0) at /data2/alja/fwWeb/cmsBetaBld/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/vector.tcc:558
#4  0x00007ffff7f7a2df in std::vector<void const*, std::allocator<void const*> >::resize (this=0x13ff4df8, __new_size=18446744073692016332, __x=@0x7fffffff9320: 0x0) at /data2/alja/fwWeb/cmsBetaBld/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/stl_vector.h:957
#5  0x00007fffd599ae1c in ROOT::read_recocLcLPFCandidate_2 (target=0x13ff4c40 "\250\373\245\325\377\177", oldObj=0x7fffffff9380) at DataFormatsParticleFlowCandidate/a/DataFormatsParticleFlowCandidate_xr.cc:2669
#6  0x00007ffff472c4e5 in TStreamerInfo::ReadBufferArtificial<char**> (this=this@entry=0x33e2c20, b=..., arr=@0x7fffffff9530: 0x14259120, aElement=aElement@entry=0x85f9470, narr=narr@entry=1529, eoffset=eoffset@entry=0)
    at /data2/alja/fwWeb/cmsBetaBld/BUILD/slc7_amd64_gcc900/lcg/root/6.25.01/root-6.25.01/io/io/src/TStreamerInfoReadBuffer.cxx:550
#7  0x00007ffff47f483c in TStreamerInfo::ReadBuffer<char**> (this=0x33e2c20, b=..., arr=<optimized out>, compinfo=0x13c373a8, first=<optimized out>, last=1, narr=1529, eoffset=0, arrayMode=1)
    at /data2/alja/fwWeb/cmsBetaBld/BUILD/slc7_amd64_gcc900/lcg/root/6.25.01/root-6.25.01/io/io/src/TStreamerInfoReadBuffer.cxx:1672
#8  0x00007ffff469259d in TStreamerInfoActions::VectorLooper::GenericRead (buf=..., start=0x13ff4c40, end=0x140b0e78, loopconfig=0x13385580, config=0x13c37390) at /data2/alja/fwWeb/cmsBetaBld/BUILD/slc7_amd64_gcc900/lcg/root/6.25.01/root-6.25.01/io/io/src/TStreamerInfoActions.cxx:1878
#9  0x00007ffff4586baf in TStreamerInfoActions::TConfiguredAction::operator() (this=0xe3d1670, buffer=..., start_collection=0x13ff4c40, end_collection=0x140b0e78, loopconf=0x13385580) at /data2/alja/fwWeb/cmsBetaBld/BUILD/slc7_amd64_gcc900/lcg/root/6.25.01/root-6.25.01/io/io/inc/TStreamerInfoActions.h:131
#10 0x00007ffff4584ca0 in TBufferFile::ApplySequence (this=0x7fffffff9620, sequence=..., start_collection=0x13ff4c40, end_collection=0x140b0e78) at /data2/alja/fwWeb/cmsBetaBld/BUILD/slc7_amd64_gcc900/lcg/root/6.25.01/root-6.25.01/io/io/src/TBufferFile.cxx:3638
#11 0x00007ffff529b9fb in TBranchElement::GetEntry (this=0x7fa4d20, entry=0, getall=0) at /data2/alja/fwWeb/cmsBetaBld/BUILD/slc7_amd64_gcc900/lcg/root/6.25.01/root-6.25.01/tree/tree/src/TBranchElement.cxx:2696
#12 0x00007ffff529b72f in TBranchElement::GetEntry (this=0x7fa2880, entry=0, getall=0) at /data2/alja/fwWeb/cmsBetaBld/BUILD/slc7_amd64_gcc900/lcg/root/6.25.01/root-6.25.01/tree/tree/src/TBranchElement.cxx:2658
#13 0x00007ffff77fc21c in fwlite::DataGetterHelper::getBranchData(edm::EDProductGetter const*, long long, fwlite::internal::Data&) const () from /data2/alja/fwWeb/cmsBetaBld/slc7_amd64_gcc900/cms/fwlite/CMSSW_11_3_4_FWLITE-cms/lib/slc7_amd64_gcc900/libDataFormatsFWLite.so
#14 0x00007ffff77feb26 in fwlite::DataGetterHelper::getByLabel(std::type_info const&, char const*, char const*, char const*, void*, long) const () from /data2/alja/fwWeb/cmsBetaBld/slc7_amd64_gcc900/cms/fwlite/CMSSW_11_3_4_FWLITE-cms/lib/slc7_amd64_gcc900/libDataFormatsFWLite.so
#15 0x00007ffff7803ef7 in fwlite::Event::getByLabel(std::type_info const&, char const*, char const*, char const*, void*) const () from /data2/alja/fwWeb/cmsBetaBld/slc7_amd64_gcc900/cms/fwlite/CMSSW_11_3_4_FWLITE-cms/lib/slc7_amd64_gcc900/libDataFormatsFWLite.so
#16 0x00007ffff7806f24 in fwlite::EventBase::getByLabelImpl(std::type_info const&, std::type_info const&, edm::InputTag const&) const () from /data2/alja/fwWeb/cmsBetaBld/slc7_amd64_gcc900/cms/fwlite/CMSSW_11_3_4_FWLITE-cms/lib/slc7_amd64_gcc900/libDataFormatsFWLite.so
#17 0x00007ffff7cc7d2d in bool edm::EventBase::getByLabel<edm::FWGenericObject>(edm::InputTag const&, edm::Handle<edm::FWGenericObject>&) const () from /data2/alja/fwWeb/cmsBetaBld/slc7_amd64_gcc900/cms/fwlite/CMSSW_11_3_4_FWLITE-cms/lib/slc7_amd64_gcc900/libFireworksCore.so
#18 0x00000000004073e4 in App::checkPFCandidatesFW (this=0x7fffffff9fd0) at /data2/matevz/CMSSW_11_3_4_FWLITE-cms/src/OssTests/BranchAddr/bin/test-bname-for.cc:122
#19 0x0000000000406547 in main (argc=2, argv=0x7fffffffa0f8) at /data2/matevz/CMSSW_11_3_4_FWLITE-cms/src/OssTests/BranchAddr/bin/test-bname-for.cc:188
```

**Comment by osschar** [comment]
@pcanal, this is a bit of a pain for CMS as we have to put an "undo commit" on all our 6.24 and master branches, e.g.:
https://github.com/cms-sw/root/commit/425ac414ef564c1cdc5fa490967d95d63df3b8eb

We probably have several incarnation of this undo in various branches :(

**Comment by pcanal** [comment]
I know :( ... This is currently the bug I am working on next.  What am I mostly missing (because I stepped away from it too long) is a reproduce of the failing case (ideally I will need a standalone reproducer to add to roottest).

**Comment by alja** [comment]
@pcanal
FYI, When applying two commits from root cms branch for IB?CMSSW_12_X_rootmaster releases the problem is gone:
https://github.com/alja/root/commit/cc4b24996738694d282a9c05768b33458a4b6190
https://github.com/root-project/root/commit/741fe64047a3cf34e824aa79e50dac1055653a22

**Comment by smuzaffar** [comment]
@osschar , note that we are only applying the revert for root master branch ( https://github.com/cms-sw/root/commits/cms/master/03d7710 ) .root 6.24 branch of cmssw ( https://github.com/cms-sw/root/commits/cms/v6-24-00-patches/f4ad42e ) does not need the revert.

**Comment by smuzaffar** [comment]
@pcanal , I am testing cms root master branch ( https://github.com/cms-sw/root/commits/cms/master/03d7710 ) without the revert of ofending commit (https://github.com/cms-sw/root/commit/f9834e30eaa01b5b8921e69bfe40681092303895 ) , once it is available then hopefully I will be able to provide you with the reproducer

**Comment by smuzaffar** [comment]
@pcanal , please use
```
/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7442/20426/install.sh
cd CMSSW_12_2_ROOT6_X_2021-11-09-2300
```
to create cmssw dev and then run the commands  in https://github.com/root-project/root/issues/7718#issuecomment-815052660 and https://github.com/root-project/root/issues/7718#issuecomment-815212145  to reproduce the errors.

**Comment by pcanal** [comment]
@smuzaffar Thanks.

**Comment by smuzaffar** [comment]
@pcanal note that `/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/7442/20426` area(for externals) and `CMSSW_12_2_ROOT6_X_2021-11-09-2300` IB will be deleted on SAT 20th NOV. If you still need to debug the issue after that date then let me know so that I can rebuilt it.

**Comment by pcanal** [comment]
@smuzaffar Thanks for the heads up.  I made significant progress and will "hopefully" not need this build that long! :)

**Comment by pcanal** [comment]
@smuzaffar I pushed several related PR to v6.24 and v6.26 (and master).  Can you verify that one of them now work properly for this case?  Thanks.

**Comment by smuzaffar** [comment]
thanks @pcanal , I have opened following PRs to tests these
-  https://github.com/cms-sw/cmsdist/pull/7601
- https://github.com/cms-sw/cmsdist/pull/7602
- https://github.com/cms-sw/cmsdist/pull/7603

**Comment by alja** [comment]
@pcanal @smuzaffar 
My tests for creating s valid edm::Handle on the sample file are now successful using CMSSW_12_3_X_2022-02-10-1100_FWLITE.

**Comment by Axel-Naumann** [comment]
Thanks! This means v6-26-00-patches is now fine for CMS, @smuzaffar ?

**Comment by smuzaffar** [comment]
yes root 6.26, after @pcanal PR https://github.com/root-project/root/pull/9927 , looks good. It has fixed the [issue](https://github.com/cms-sw/cmssw/issues/36908) and IBs look good. We still have random root file [read error](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_ROOT626_X_2022-02-20-2300/pyRelValMatrixLogs/run/250206.18_ZMM_13UP18+ZMM_13UP18INPUT+DIGIPRMXUP18_PU25+RECOPRMXUP18_PU25_L1TMuDQM+HARVESTUP18_PU25_L1TMuDQM/step2_ZMM_13UP18+ZMM_13UP18INPUT+DIGIPRMXUP18_PU25+RECOPRMXUP18_PU25_L1TMuDQM+HARVESTUP18_PU25_L1TMuDQM.log#/749438-749438) but I do not think those are related to root change.

**Comment by pcanal** [comment]
Fair enough.  Let's close this issue and re-open a new one if needed be.
