### ISSUE TITLE
cling error recovery issues

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#7970]
### Describe the bug
```
root [1] .rawInput
root [2] std::vector<short> getV() { return {42}; }
root [3] .rawInput
root [4] getV()[0].foo()
```
and that last line shows an error, good! But now:
```
root [5] getV()[0]
IncrementalExecutor::executeFunction: symbol '_ZSt8_DestroyIPssEvT_S1_RSaIT0_E' unresolved while linking [cling interface function]!
You are probably missing the definition of void std::_Destroy<short*, short>(short*, short*, std::allocator<short>&)
Maybe you need to load the corresponding shared library?
```

**Comment by jalopezg-r00t** [comment]
Thanks for the report, @Axel-Naumann!  We already have several issues with seemingly the same origin (removing symbols from the JIT that are not re-emitted, apparently because they came from a PCH/module).

I was taking a look into this last week, but still don't have a fix for it.  I will continue working on it.  :-)

**Comment by Axel-Naumann** [comment]
Those I know of - but here the specialization is *not* coming from the PCH/PCM. (You can try to `MyClass` if you don't believe me ;-) )

**Comment by hahnjo** [comment]
Unfortunately the second reproducer still fails for me in `master` - probably because of my last commit to make the tests pass on macOS :neutral_face:

**Comment by dpiparo** [comment]
I cannot reproduce on (mac, linux)x(6.30.04,master). I close the issue, please do not hesitate to re-open if I am missing something (@hahnjo @devajithvs)

**Comment by hahnjo** [comment]
I still get exactly the error described in the summary with `master`:
```
   ----------------------------------------------------------------------------
  | Welcome to ROOT 6.31/01                                  https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers           |
  | Built for linuxx8664gcc on Feb 05 2024, 07:24:23                           |
  | From heads/ntuple-RPageNullSink@v6-31-01-913-gfdecca9b4d                   |
  | With clang version 16.0.6 (Red Hat 16.0.6-2.module_el8.9.0+3621+df7f7146)  |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'            |
   ----------------------------------------------------------------------------

root [0] .rawInput
Using raw input
root [1] std::vector<short> getV() { return {42}; }
root [2] .rawInput
Not using raw input
root [3] getV()[0].foo()
ROOT_prompt_3:1:10: error: member reference base type 'value_type' (aka 'short') is not a structure or union
getV()[0].foo()
~~~~~~~~~^~~~
root [4] getV()[0]
IncrementalExecutor::executeFunction: symbol '_ZSt8_DestroyIPssEvT_S1_RSaIT0_E' unresolved while linking [cling interface function]!
You are probably missing the definition of void std::_Destroy<short*, short>(short*, short*, std::allocator<short>&)
Maybe you need to load the corresponding shared library?
```

**Comment by ferdymercury** [comment]
This seems solved with current master ! At least on Ubu22

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.37.01                        https://root.cern |
  | (c) 1995-2025, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Oct 07 2025, 11:44:59                 |
  | From heads/master@v6-29-01-17355-g412a499143b                    |
  | With g++ (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0                 |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] .rawInput
Using raw input
root [1] std::vector<short> getV() { return {42}; }
root [2] .rawInput
Not using raw input
root [3]  getV()[0].foo()
ROOT_prompt_3:1:10: error: member reference base type 'value_type' (aka 'short') is not a structure or union
getV()[0].foo()
~~~~~~~~~^~~~
root [4] getV()[0]
(short) 42
root [5] 
```

**Comment by hahnjo** [comment]
Can still reproduce https://github.com/root-project/root/issues/7970#issuecomment-1926373568

**Comment by ferdymercury** [comment]
Is it maybe a clang-specific issue? (Since it works with g++11 on Ubu22)

**Comment by hahnjo** [comment]
No, it also happens when built with GCC 8.5.0 on AlmaLinux 8. It may have to do with the version of `libstdc++`...

**Comment by ferdymercury** [comment]
Fails for me on master (LLVM22) and Ubu24 (gcc-13)
