### ISSUE TITLE
Crash when defining something in the Detail namespace after a lookup of that namespace

### ISSUE THREAD

**Issue by etejedor** [root-project/root#8828]
As explained in https://github.com/root-project/root/issues/8745, if we look up the `Detail` namespace first and then define something else in it, there is an assertion failure. That crash does not happen if there is no prior lookup. Example:

```
root [0] auto c = TClass::GetClass("Detail")
(TClass *) @0x7fffd0908fc0
root [1] namespace Detail { int i; }
root.exe: /home/etejedor/root/fork/root/interpreter/llvm/src/include/llvm/Support/Casting.h:105: static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = clang::TagType; From = clang::Type]: Assertion `Val && "isa<> used on a null pointer"' failed.
```

**Comment by hahnjo** [comment]
@etejedor Do you have a stack trace? There's also `isa_and_nonnull`, so if some return value can be validly null, it may be as easy as using that?

**Comment by etejedor** [comment]
@hahnjo there is no stack trace unfortunately, just the assertion failure message. Were you able to reproduce yourself? I can reproduce on both my laptop and desktop machines, Ubuntu and CentOS7 with master, but not e.g. on lxplus.

As for the use of `isa_and_nonnull`, @Axel-Naumann can better comment.

**Comment by hahnjo** [comment]
> @hahnjo there is no stack trace unfortunately, just the assertion failure message. Were you able to reproduce yourself? I can reproduce on both my laptop and desktop machines, Ubuntu and CentOS7 with master, but not e.g. on lxplus.

I didn't try yet, first checking if you might have more information that would accelerate diagnosis. I will build a debug version of Cling and try to reproduce :+1: with Axel and Javi on vacation, I might take a look if it's easy to fix.

**Comment by hahnjo** [comment]
Hm, actually I cannot reproduce this, at least with the example give above:
```
root [0] auto c = TClass::GetClass("Detail")
(TClass *) nullptr
root [1] namespace Detail { int i; }
root [2]
```

Do I have to (auto)load something during startup?

**Comment by etejedor** [comment]
I didn't do anything special nor load anything, still that `Detail` namespace is there. I see this with debug builds with roottest enabled, besides that there is no particular setting.

**Comment by hahnjo** [comment]
Okay, I just noticed that you wrote you cannot reproduce on lxplus, so I'm not doing something entirely wrong. The two most likely causes are that you have some local `.rootrc` file (try with `root -n`), or that both lxplus and me are missing some optional dependencies that activate some problematic loading. From CMake, I get: `asimage builtin_afterimage builtin_clang builtin_cling builtin_ftgl builtin_gl2ps builtin_glew builtin_llvm builtin_openui5 builtin_vdt builtin_xxhash clad dataframe davix exceptions gdml http imt mathmore mlp minuit2 mysql opengl pgsql pyroot pythia8 roofit webgui root7 rpath runtime_cxxmodules shared sqlite ssl tmva tmva-cpu tmva-pymva spectrum vdt x11 xml xrootd` Maybe you have some additional packages here?

**Comment by hahnjo** [comment]
@etejedor and me finally figured out what's the difference between the builds: The problem only arises if building with C++14 which pulls in `ROOT/RNotFn.hxx`, defining `std::Detail`. Because of the implicit `using namespace std;` this ends up conflicting with `namespace Detail` defined in the `root` prompt. FWIW here's the full `backtrace` from a Debug build (which gives less information by default compared to Release because of `assert`s?!):
```
#0  0x00007ffff648c37f in raise () from /lib64/libc.so.6
#1  0x00007ffff6476db5 in abort () from /lib64/libc.so.6
#2  0x00007ffff6476c89 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007ffff6484a76 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fffec1c4bb1 in llvm::isa_impl_cl<clang::TagType, clang::Type const*>::doit (Val=0x0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/Support/Casting.h:105
#5  0x00007fffec1c296e in llvm::isa_impl_wrap<clang::TagType, clang::Type const*, clang::Type const*>::doit (Val=@0x7fffffffaa08: 0x0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/Support/Casting.h:132
#6  0x00007fffec1bf2ff in llvm::isa_impl_wrap<clang::TagType, clang::Type const* const, clang::Type const*>::doit (Val=@0x7fffffffaa48: 0x0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/Support/Casting.h:123
#7  0x00007fffec1ba2ee in llvm::isa<clang::TagType, clang::Type const*> (Val=@0x7fffffffaa48: 0x0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/Support/Casting.h:143
#8  0x00007fffec1b56b5 in llvm::dyn_cast<clang::TagType, clang::Type const> (Val=0x0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/include/llvm/Support/Casting.h:343
#9  0x00007fffec44dae0 in clang::Type::getAs<clang::TagType> (this=0x0) at /home/jhahnfel/ROOT/src/interpreter/llvm/src/tools/clang/include/clang/AST/Type.h:6858
#10 0x00007fffec46bf1c in TClingClassInfo::Init (this=0x1933310, tag=...) at /home/jhahnfel/ROOT/src/core/metacling/src/TClingClassInfo.cxx:775
#11 0x00007fffec31a41b in TCling::RefreshClassInfo (this=0x696f40, cl=0x1886f90, def=0x19e3ac0, alias=false) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:6629
#12 0x00007fffec31a951 in TCling::UpdateClassInfoWithDecl (this=0x696f40, ND=0x19e3ac0) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:6706
#13 0x00007fffec2feb4f in TCling__UpdateClassInfo (TD=0x19e3ac0) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:390
#14 0x00007fffec2ff3bf in TCling::HandleNewDecl (this=0x696f40, DV=0x19e3ac0, isDeserialized=false, modifiedTClasses=std::set with 0 elements) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:518
#15 0x00007fffec31acaf in TCling::UpdateListsOnCommitted (this=0x696f40, T=...) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:6773
#16 0x00007fffec2ff5d6 in TCling__UpdateListsOnCommitted (T=...) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:554
#17 0x00007fffec45276f in TClingCallbacks::TransactionCommitted (this=0x1244d20, T=...) at /home/jhahnfel/ROOT/src/core/metacling/src/TClingCallbacks.cxx:872
#18 0x00007fffec52fc5f in cling::MultiplexInterpreterCallbacks::TransactionCommitted (this=0x720d70, T=...) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/MultiplexInterpreterCallbacks.h:83
#19 0x00007fffec67437d in cling::IncrementalParser::commitTransaction (this=0x6a7b50, PRT=..., ClearDiagClient=true) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/IncrementalParser.cpp:630
#20 0x00007fffec674b5d in cling::IncrementalParser::Compile (this=0x6a7b50, input=..., Opts=...) at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/IncrementalParser.cpp:775
#21 0x00007fffec52c5db in cling::Interpreter::DeclareInternal (this=0x697c30, input="#line 1 \"ROOT_prompt_1\"\nnamespace Detail { int i; }", CO=..., T=0x0)
    at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/Interpreter.cpp:1341
#22 0x00007fffec52a961 in cling::Interpreter::process (this=0x697c30, input="#line 1 \"ROOT_prompt_1\"\nnamespace Detail { int i; }", V=0x7fffffffb6d0, T=0x0, disableValuePrinting=false)
    at /home/jhahnfel/ROOT/src/interpreter/cling/lib/Interpreter/Interpreter.cpp:819
#23 0x00007fffec74a8a1 in cling::MetaProcessor::process (this=0x1069b10, input_line=..., compRes=@0x7fffffffb6cc: cling::Interpreter::kSuccess, result=0x7fffffffb6d0, disableValuePrinting=false)
    at /home/jhahnfel/ROOT/src/interpreter/cling/lib/MetaProcessor/MetaProcessor.cpp:341
#24 0x00007fffec3097e3 in HandleInterpreterException (metaProcessor=0x1069b10, input_line=0x195b760 "#line 1 \"ROOT_prompt_1\"\nnamespace Detail { int i; }", compRes=@0x7fffffffb6cc: cling::Interpreter::kSuccess, result=0x7fffffffb6d0)
    at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:2435
#25 0x00007fffec30a3ce in TCling::ProcessLine (this=0x696f40, line=0x1928420 "#line 1 \"ROOT_prompt_1\"\nnamespace Detail { int i; }", error=0x7fffffffba9c) at /home/jhahnfel/ROOT/src/core/metacling/src/TCling.cxx:2595
#26 0x00007ffff7621d55 in TApplication::ProcessLine (this=0x6800b0, line=0x1928420 "#line 1 \"ROOT_prompt_1\"\nnamespace Detail { int i; }", sync=false, err=0x7fffffffba9c) at /home/jhahnfel/ROOT/src/core/base/src/TApplication.cxx:1452
#27 0x00007ffff7bb80e2 in TRint::ProcessLineNr (this=0x6800b0, filestem=0x7ffff7bc672f "ROOT_prompt_", line=0x1521090 "namespace Detail { int i; }", error=0x7fffffffba9c) at /home/jhahnfel/ROOT/src/core/rint/src/TRint.cxx:751
#28 0x00007ffff7bb79da in TRint::HandleTermInput (this=0x6800b0) at /home/jhahnfel/ROOT/src/core/rint/src/TRint.cxx:612
#29 0x00007ffff7bb54e9 in TTermInputHandler::Notify (this=0x14bbda0) at /home/jhahnfel/ROOT/src/core/rint/src/TRint.cxx:132
#30 0x00007ffff7bb9885 in TTermInputHandler::ReadNotify (this=0x14bbda0) at /home/jhahnfel/ROOT/src/core/rint/src/TRint.cxx:124
#31 0x00007ffff77a4140 in TUnixSystem::CheckDescriptors (this=0x628800) at /home/jhahnfel/ROOT/src/core/unix/src/TUnixSystem.cxx:1322
#32 0x00007ffff77a356b in TUnixSystem::DispatchOneEvent (this=0x628800, pendingOnly=false) at /home/jhahnfel/ROOT/src/core/unix/src/TUnixSystem.cxx:1077
#33 0x00007ffff7694f83 in TSystem::InnerLoop (this=0x628800) at /home/jhahnfel/ROOT/src/core/base/src/TSystem.cxx:406
#34 0x00007ffff7694d31 in TSystem::Run (this=0x628800) at /home/jhahnfel/ROOT/src/core/base/src/TSystem.cxx:356
#35 0x00007ffff76227af in TApplication::Run (this=0x6800b0, retrn=false) at /home/jhahnfel/ROOT/src/core/base/src/TApplication.cxx:1604
#36 0x00007ffff7bb6d0e in TRint::Run (this=0x6800b0, retrn=false) at /home/jhahnfel/ROOT/src/core/rint/src/TRint.cxx:463
#37 0x0000000000400a58 in main (argc=1, argv=0x7fffffffdf98) at /home/jhahnfel/ROOT/src/main/src/rmain.cxx:30
```

Interestingly
```
root [0] namespace Detail { int i; }
root [1] auto c = TClass::GetClass("Detail")
(TClass *) nullptr
```

**Comment by hahnjo** [comment]
I've tried to look into this, and I'm becoming more and more convinced that the underlying problem is related to `core/meta/` and special handling of `namespace std`, and not to the general Cling machinery in the background. To recap (the following is with a C++17 build, so I can define `std::Detail` as I wish):
```
root [0] namespace std { namespace Detail { } }
root [1] auto c = TClass::GetClass("Detail")
(TClass *) @0x7ffff7f9cfc0
root [2] namespace Detail { }

 *** Break *** segmentation violation
```
but
```
root [0] namespace A { namespace Detail { } }
root [1] using namespace A;
root [2] TClass::GetClass("Detail")
(TClass *) 0x31856a0
root [3] namespace Detail { }
root [4] TClass::GetClass("Detail")
(TClass *) nullptr
```
is fine (at least the behavior that `TClass::GetClass("Detail")` returns `nullptr` is consistent, albeit unexpected).

I think it's more productive to ask Axel to investigate, he knows the ins and outs of `core/meta`...

**Comment by Axel-Naumann** [comment]
Looks like `TClingClassInfo::Init` is confused, and thinks something should be a `Type` where there's no type:
```
#9  0x00007fffec44dae0 in clang::Type::getAs<clang::TagType> (this=0x0)
``` 
Can you give it another stab, @hahnjo ? For instance trying to understand why `TClingClassInfo` thinks there should be a type?

**Comment by hahnjo** [comment]
> For instance trying to understand why `TClingClassInfo` thinks there should be a type?

Ok, I think `TCling::RefreshClassInfo` incorrectly assumes that any redeclaration that is different from the previous definition must be a type, while in fact the scenario created here redefines a namespace - I assume they end up being detected as redefinition because `std::` is special and normalized out? If that assessment is correct, #9089 should be the obvious fix.

**Comment by hahnjo** [comment]
Aha, now I understand more of the rationale behind the code. Updating a class `K` seems to work, at least `GetDataMember("i")` returns something after giving the full definition (while it is `nullptr` before) - I hope this is tested somewhere? I didn't check, if not we should definitely have a test case here!

Regarding the namespaces, the following test gives what I would expect:
```
root [0] namespace std { namespace ns { } }
root [1] auto c = TClass::GetClass("ns");
root [2] c->GetDataMember("a")
(TDataMember *) nullptr
root [3] namespace std { namespace ns { int a = 0; } }
root [4] c->GetDataMember("a")
(TDataMember *) 0x27eed80
root [5] namespace ns { int b = 1; }
root [6] c->GetDataMember("b")
(TDataMember *) nullptr
```

The only thing that doesn't work is getting a `TClass` of `::ns`, ie
```
root [7] TClass::GetClass("ns")->GetDataMember("b")
(TDataMember *) nullptr
```

I think this is fine since you cannot use `ns` anyway:
```
root [8] ns::b
ROOT_prompt_8:1:1: error: reference to 'ns' is ambiguous
ns::b
^
ROOT_prompt_5:1:11: note: candidate found by name lookup is 'ns'
namespace ns { int b = 1; }
          ^
ROOT_prompt_3:1:27: note: candidate found by name lookup is 'std::ns'
namespace std { namespace ns { int a = 0; } }
                          ^
```

**Comment by Axel-Naumann** [comment]
Exactly. Talking to Philippe we indeed need to decide how to deal with this case of `std::foo` vs `::foo`. We can delay the decision point by renaming `std::Detail` injected by ROOT (#9093).

**Comment by guitargeek** [comment]
I have tried to reproduce this issue with several namespace names, like `Detail`, `ROOT`, or `RooFit`, but it can't be reproduced anymore. Therefore, I conclude this is fixed. At least in ROOT `master`.

**Comment by hahnjo** [comment]
https://github.com/root-project/root/issues/8828#issuecomment-902721993 still fails perfectly fine for me. It's not as much of a problem anymore since ROOT's backports don't inject into `std::Detail` anymore, but the problem is still there!

**Comment by guitargeek** [comment]
Ok you can always construct something that fails, but the relevance is still debatable if nobody injects into `std::Detail`.

**Comment by pcanal** [comment]
Summary:
* This appears because stripping `std::` allows 2 entities to have the same normalized name
* This can also appears in case of inline namespace (but does not seem to cause the same problem)
* In both scenario we ends up a (delayed diagnosed :( ) ambiguous symbol.
* The UpdateClassInfo machinery somehow only fails in the std case.
* The error handling could be improved by tweaking in `TCling::RefreshClassInfo(TClass *cl, const clang::NamedDecl *def, bool alias)`:
```
      if (!oldDef || (def && def != oldDef)) {
         cl->ResetCaches();
         TClass::RemoveClassDeclId(cci->GetDeclId());
         if (def) {
            // It's a tag decl, not a namespace decl.
            cci->Init(*cci->GetType());
```
to detect that even though old and new (`def` and `oldDef`) decl are different they are still a namespace and issue an error rather than calling `cci->Init` which (even if we passed the right type) would still semantically do the 'wrong' thing (technically updating the `TClass` for the first namespace to now look at the second namespace).


```
root [0] gInterpreter->Declare("inline namespace __inlinens__ { namespace Detail {} } ")
(bool) true
root [1] auto c = TClass::GetClass("Detail")
(TClass *) 0x14e1048d0
root [2] namespace Detail {}
```
but 
```
root [0] namespace std { namespace Detail {} }
root [1] auto c = TClass::GetClass("Detail")
(TClass *) 0x1497316a0
root [2] namespace Detail {}
Assertion failed: (detail::isPresent(Val) && "dyn_cast on a non-existent value"), function dyn_cast, file Casting.h, line 663.
Abort trap: 6
```

**Comment by pcanal** [comment]
Humm ... the inline namespace was a red-herring ...  Doing:
```
inline namespace __inline_ns__ { namespace Detail { } } 
namespace Detail {}
```
does **not** create 2 distinct namespace, they are the same.

**Comment by pcanal** [comment]
The fix is 'simple':
```
diff --git a/core/metacling/src/TCling.cxx b/core/metacling/src/TCling.cxx
index 7fe65825ea..656396ffcd 100644
--- a/core/metacling/src/TCling.cxx
+++ b/core/metacling/src/TCling.cxx
@@ -6646,9 +6646,13 @@ void TCling::RefreshClassInfo(TClass *cl, const clang::NamedDecl *def, bool alia
          cl->ResetCaches();
          TClass::RemoveClassDeclId(cci->GetDeclId());
          if (def) {
-            // It's a tag decl, not a namespace decl.
-            cci->Init(*cci->GetType());
-            TClass::AddClassToDeclIdMap(cci->GetDeclId(), cl);
+            if (cci->GetType()) {
+               // It's a tag decl, not a namespace decl.
+               cci->Init(*cci->GetType());
+               TClass::AddClassToDeclIdMap(cci->GetDeclId(), cl);
+            } else {
+               Error("RefreshClassInfo", "Should not need to update the classInfo a non type decl: %s", oldDef->getNameAsString().c_str());
+            }
          }
       }
    } else if (!cl->TestBit(TClass::kLoading) && !cl->fHasRootPcmInfo) {
```
```
root [0] namespace std { namespace Detail {} }
root [1] auto c = TClass::GetClass("Detail")
(TClass *) 0x12ef3d7b0
root [2] namespace Detail {}
Error in <TInterpreter::RefreshClassInfo>: Should not need to update the classInfo a non type decl: Detail
```

**Comment by hahnjo** [comment]
> The fix is 'simple':

Well yes, see https://github.com/root-project/root/pull/9089 and discussion

**Comment by pcanal** [comment]
Yes my currently proposed patch is 'substantially' different and apply the recommendation https://github.com/root-project/root/pull/9089#issuecomment-950705276

**Comment by pcanal** [comment]
I opened https://github.com/root-project/root/pull/16540
